---
# tasks file for deploy_apache_web
  - name: Install Apache2 
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian" 

  - name: Generate INDEX.HTML file
    template: 
      src=index.j2
      dest={{ destin_folder }}/index.html
      mode=0555
    notify: Restart apache2    
  
  - name: Copy MyHomePage to Servers
    copy:
      src={{ item }}
      dest={{ destin_folder }}
      mode=0555
    with_fileglob: "{{ source_folder }}/*.*"
    loop:
      - "kolopo1.png"
      - "kolopo2.png"
      - "kolopo3.png"
      - "kolopo4.png"
    notify: Restart apache2
 
  - name: Start Service Apache2 and enable
    service:
       name=apache2
       state=started
       enabled=yes
