---
- name: Install Apache2
  hosts: all
  become: yes
 
  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian" 
  - name: Copy MyHomePage to Servers
    copy:
       src={{ source_file }}
       dest={{ destin_file }}
       mode=0555
    notify: Restart apache2
 
  - name: Start Service Apache2 and enable
    service:
       name=apache2
       state=started
       enabled=yes

  handlers:
  - name: Restart apache2
    service:
       name=apache2
       state=started
