---
- name: Install Apache2
  hosts: all
  become: yes

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: absent

  - name: Start Service Apche2 and enable
    service:
       name=apache2
       state=started
       enabled=yes
