---
- name: Loops Playbook
  hosts: all
  become: yes

  tasks:
  - name: Say Hi to All
    debug:
      msg="Hi {{ item }}"
    loop:
      - "Dmitri"
      - "Vlad"    
      - "Kirill"

  - name: Loop Until Example
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZ") == false

  - name: Print Final Output
    debug:
      var: output.stdout

  - name: Install Packages
    apt:
      name={{ item }}
      state=latest
    loop:
       - python
       - tree
