---
- name: Playbook
  hosts: all 
  become: yes

  vars:
   mytext: "Privet"
   
  tasks:
  - name: Ping test
    ping:

  - name: Updating
    shell: echo UPDATING Database
    run_once: true

  - name: Create File 1
    copy:
     dest: /home/file1.txt
     content: |
       This is File#1
       On ENGLISH Hello
       On RUSSIAN {{ mytext }}
    delegate_to: linux3

  - name: Create File 2
    copy:
     dest: /home/file2.txt     
     content: |
       This is File#2
       On ENGLISH Hello
       On RUSSIAN {{ mytext }}
   
  - name: Reboot
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait till my servers
    wait_for:
     host: "{{ inventory_hostname }}"
     state: started
     delay: 5
     timeout: 40
